
#Settings for the modular storage system
[storage]
	#If true we clear the search field when opening the GUI for the modular storage. Set to false if you don't want that
	clearSearchOnOpen = true
	#Foreground color for group lines
	#Range: > 0
	groupForeground = 0
	#If true we automatically set the focus on the search field when opening the GUI for the modular storage. Set to false if you don't want that
	autofocusSearch = false
	#Background color for group lines
	#Range: > 0
	groupBackground = 0

